baseURL = "https://leopold.page/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Leopold Pfeiffer"
theme = "anatole-fork"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true


[params]
title = "Leopold Pfeiffer"
author = "Leopold Pfeiffer"
description = "Software Engineer"
profilePicture = "images/small_square.png"
keywords = "personal website"
favicon = "favicons/"
mainSections = [""]
doNotLoadAnimations = false
displayMode = "dark"

## Date formats
singleDateFormat = "Jan 2006"
indexDateFormat = "Jan 2006"
listDateFormat = "Jan 2006"

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/leopoldpfeiffer"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/leo-pfeiffer"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:me@leopold.page"

[menu]

  [[menu.main]]
  name = "home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "education"
  identifier = "education"
  weight = 200
  url = "/education/"

  [[menu.main]]
  name = "work experience"
  identifier = "work experience"
  weight = 300
  url = "/work-experience/"

  [[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 400
  url = "/projects/"

  [[menu.main]]
  name = "skills"
  identifier = "skills"
  weight = 500
  url = "/skills/"

  [[menu.main]]
  name = "about"
  weight = 600
  identifier = "about"
  url = "/about/"

