baseURL = "https://leopold.page/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Leopold Pfeiffer"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[params]
title = "Leopold Pfeiffer"
author = "Leopold Pfeiffer"
description = "Software Engineer"
profilePicture = "images/small_square.png"
keywords = "personal website"
favicon = "favicons/"
mainSections = ["post"]
doNotLoadAnimations = false

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/leopoldpfeiffer"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/leo-pfeiffer"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:me@leopold.page"

